//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int Ad_id { get; set; }
    public string Ad_FirstName { get; set; }
    public string Ad_LastName { get; set; }
    public string Ad_Email { get; set; }
    public string Ad_Password { get; set; }
    public string Ad_Mobile { get; set; }
    public string Ad_JobDescription { get; set; }
    public string Ad_image { get; set; }
}

public partial class Comment
{
    public int Comment_ID { get; set; }
    public string Comment_Message { get; set; }
    public int Post_ID { get; set; }
    public int Cust_ID { get; set; }
    public int PM_ID { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual PM PM { get; set; }
    public virtual Project Project { get; set; }
}

public partial class CurrentProject
{
    public int id { get; set; }
    public int Post_ID { get; set; }
    public string Post_Description { get; set; }
    public int PM_ID { get; set; }
    public Nullable<int> TL_ID { get; set; }
    public int Cust_ID { get; set; }
    public string Start_Date { get; set; }
    public string DeadLine { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual PM PM { get; set; }
    public virtual TL TL { get; set; }
}

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.Comments = new HashSet<Comment>();
        this.CurrentProjects = new HashSet<CurrentProject>();
        this.PreviousProjects = new HashSet<PreviousProject>();
        this.Projects = new HashSet<Project>();
    }

    public int Cust_ID { get; set; }
    public string Cust_FirstName { get; set; }
    public string Cust_LastName { get; set; }
    public string Cust_Email { get; set; }
    public string Cust_Password { get; set; }
    public string Cust_Mobile { get; set; }
    public string Cust_JobDescription { get; set; }
    public string Cust_image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CurrentProject> CurrentProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PreviousProject> PreviousProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project> Projects { get; set; }
}

public partial class JD
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public JD()
    {
        this.JDCurProjects = new HashSet<JDCurProject>();
        this.JDPreProjects = new HashSet<JDPreProject>();
    }

    public int JD_ID { get; set; }
    public string JD_FirstName { get; set; }
    public string JD_LastName { get; set; }
    public string JD_Email { get; set; }
    public string JD_Password { get; set; }
    public string JD_Mobile { get; set; }
    public string JD_JobDescription { get; set; }
    public string JD_image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JDCurProject> JDCurProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JDPreProject> JDPreProjects { get; set; }
}

public partial class JDCurProject
{
    public int id { get; set; }
    public int JD_id { get; set; }
    public int Post_id { get; set; }

    public virtual JD JD { get; set; }
}

public partial class JDPreProject
{
    public int id { get; set; }
    public int JD_id { get; set; }
    public int Post_id { get; set; }

    public virtual JD JD { get; set; }
}

public partial class Notification
{
    public int not_id { get; set; }
    public int p1_id { get; set; }
    public string actor1_name { get; set; }
    public Nullable<int> P2_id { get; set; }
    public string actor2_name { get; set; }
    public string not_message { get; set; }
    public string date { get; set; }
    public int Post_ID { get; set; }
}

public partial class PM
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PM()
    {
        this.Comments = new HashSet<Comment>();
        this.CurrentProjects = new HashSet<CurrentProject>();
        this.PreviousProjects = new HashSet<PreviousProject>();
        this.Projects = new HashSet<Project>();
    }

    public int PM_id { get; set; }
    public string PM_FirstName { get; set; }
    public string PM_LastName { get; set; }
    public string PM_Email { get; set; }
    public string PM_Password { get; set; }
    public string PM_Mobile { get; set; }
    public string PM_Jobdescription { get; set; }
    public string PM_image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CurrentProject> CurrentProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PreviousProject> PreviousProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project> Projects { get; set; }
}

public partial class PreviousProject
{
    public int id { get; set; }
    public int Post_ID { get; set; }
    public string Post_Description { get; set; }
    public int PM_ID { get; set; }
    public int TL_ID { get; set; }
    public int Cust_ID { get; set; }
    public string is_complete { get; set; }
    public int evaluation { get; set; }
    public string EndData { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual PM PM { get; set; }
    public virtual TL TL { get; set; }
}

public partial class Project
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project()
    {
        this.Comments = new HashSet<Comment>();
    }

    public int Post_ID { get; set; }
    public string Post_Description { get; set; }
    public int Cust_ID { get; set; }
    public System.DateTime Post_Time { get; set; }
    public string is_admin { get; set; }
    public Nullable<int> PM_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Customer Customer { get; set; }
    public virtual PM PM { get; set; }
}

public partial class Role
{
    public int rid { get; set; }
    public string rname { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class TL
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TL()
    {
        this.CurrentProjects = new HashSet<CurrentProject>();
        this.PreviousProjects = new HashSet<PreviousProject>();
    }

    public int TL_ID { get; set; }
    public string TL_FirstName { get; set; }
    public string TL_LastName { get; set; }
    public string TL_Email { get; set; }
    public string TL_Password { get; set; }
    public string TL_Mobile { get; set; }
    public string TL_JobDescription { get; set; }
    public string TL_image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CurrentProject> CurrentProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PreviousProject> PreviousProjects { get; set; }
}
