//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PMSDBEntities1 : DbContext
{
    public PMSDBEntities1()
        : base("name=PMSDBEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Admin> Admins { get; set; }
    public virtual DbSet<Comment> Comments { get; set; }
    public virtual DbSet<CurrentProject> CurrentProjects { get; set; }
    public virtual DbSet<Customer> Customers { get; set; }
    public virtual DbSet<JD> JDs { get; set; }
    public virtual DbSet<JDCurProject> JDCurProjects { get; set; }
    public virtual DbSet<JDPreProject> JDPreProjects { get; set; }
    public virtual DbSet<Notification> Notifications { get; set; }
    public virtual DbSet<PM> PMs { get; set; }
    public virtual DbSet<PreviousProject> PreviousProjects { get; set; }
    public virtual DbSet<Project> Projects { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TL> TLs { get; set; }
}
