//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Ad_id { get; set; }
        public string Ad_FirstName { get; set; }
        public string Ad_LastName { get; set; }
        public string Ad_Email { get; set; }
        public string Ad_Password { get; set; }
        public string Ad_Mobile { get; set; }
        public string Ad_JobDescription { get; set; }
        public string Ad_image { get; set; }
    }
}
