//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuniorDeveloper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JuniorDeveloper()
        {
            this.JdCurrentProjects = new HashSet<JdCurrentProject>();
            this.JdPreProjects = new HashSet<JdPreProject>();
        }
    
        public int JD_ID { get; set; }
        public string JD_FirstName { get; set; }
        public string JD_LastName { get; set; }
        public string JD_Email { get; set; }
        public string JD_Password { get; set; }
        public string JD_Mobile { get; set; }
        public string JD_JobDescription { get; set; }
        public string JD_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JdCurrentProject> JdCurrentProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JdPreProject> JdPreProjects { get; set; }
    }
}
