//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_Id { get; set; }
        public int Person1_Id { get; set; }
        public string Actor1_Name { get; set; }
        public Nullable<int> Person2_Id { get; set; }
        public string Actor2_name { get; set; }
        public string Message { get; set; }
        public string Date { get; set; }
        public int Post_ID { get; set; }
    }
}
