//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreProject
    {
        public int id { get; set; }
        public int Post_ID { get; set; }
        public string Post_Description { get; set; }
        public int PM_ID { get; set; }
        public int TL_ID { get; set; }
        public int Cust_ID { get; set; }
        public string is_complete { get; set; }
        public int evaluation { get; set; }
        public string EndData { get; set; }
    }
}
