//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Comments = new HashSet<Comment>();
            this.CurrentProjects = new HashSet<CurrentProject>();
            this.JdCurrentProjects = new HashSet<JdCurrentProject>();
        }
    
        public int Post_ID { get; set; }
        public string Post_Description { get; set; }
        public int Cust_ID { get; set; }
        public System.DateTime Post_Time { get; set; }
        public string is_admin { get; set; }
        public Nullable<int> PM_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentProject> CurrentProjects { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JdCurrentProject> JdCurrentProjects { get; set; }
        public virtual ProjectManager ProjectManager { get; set; }
    }
}
