//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamLeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamLeader()
        {
            this.CurrentProjects = new HashSet<CurrentProject>();
        }
    
        public int TL_ID { get; set; }
        public string TL_FirstName { get; set; }
        public string TL_LastName { get; set; }
        public string TL_Email { get; set; }
        public string TL_Password { get; set; }
        public string TL_Mobile { get; set; }
        public string TL_JobDescription { get; set; }
        public string TL_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentProject> CurrentProjects { get; set; }
    }
}
